baseURL = "https://xavierxizhang.github.io/"
languageCode = "zh-cn"
title = "Xavier Xi Zhang 张曦"
theme = "PaperMod"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 2
  [[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 3
  [[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 4
  [[menu.main]]
    name = "My Story"
    url = "/my-story/"
    weight = 5
